### ISSUE TITLE
Tooterminal画面のmargin:8px には意味がありますか？

### ISSUE THREAD

**Issue by fiwa-wkrf** [wd-shiroma/tooterminal#8]
Vivaldiブラウザのタブタイリングで、横に複数Tooterminalを並べた際にこのマージン指定で余白部分が目立ち、表示される情報量が減っているのがもったいないと以前のバージョンから思っていました。
この値を減らすと弊害があるならば諦めますが、特に問題が無いならばマージンの値の再考をお願いしたいです。

![tooterminal margin8px_20180926](https://user-images.githubusercontent.com/43440086/46071465-0911b280-c1bb-11e8-8fec-ec847ba645d7.png)
![tooterminal_vivaldi 4 _1_20180926](https://user-images.githubusercontent.com/43440086/46071608-6279e180-c1bb-11e8-9b4a-afd797f7566f.png)

**Comment by fiwa-wkrf** [comment]
すみません。
このIssue取り下げさせてください。

**Comment by wd-shiroma** [comment]
閉じさせて貰います
I close this issue.
